### ISSUE TITLE
No new locations

### ISSUE THREAD

**Issue by narnikgamarnikus** [jazztickets/choria#1]
It is not clear where to go next.
25 level - and there are no new locations

**Comment by jazztickets** [comment]
What version are you playing?

**Comment by narnikgamarnikus** [comment]
0.4.2-1

**Comment by jazztickets** [comment]
Did you get to the 3rd town? You may have beat the game then.

You need to clone the repo and build 0.9.0r1119. That's when the real fun begins.

**Comment by narnikgamarnikus** [comment]
Thanks!
